project_id = "ucjnonpozhzuyjuowwdx"

[functions.chat]
verify_jwt = false

[functions.update-gps]
verify_jwt = false

[functions.ai-support]
verify_jwt = false

[functions.damage-detection]
verify_jwt = false
